runs:
  using: composite
  steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          rubygems: 3.4.22
          bundler: Gemfile.lock
          bundler-cache: true
