name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          rubygems: 3.4.22
          bundler-cache: true

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          rubygems: 3.4.22
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare test test:system

  checks:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          rubygems: 3.4.22
          bundler-cache: true

      - name: Check Bundler version
        run: bundler --version

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager --no-progress --confidence-level 2
